const extractjobSkills = (jobDescription) => {

    const keywordDatabase = [
        "C",
        "C++",
        "C#",
        "Java",
        "Python",
        "JavaScript",
        "TypeScript",
        "Go",
        "Golang",
        "Rust",
        "Kotlin",
        "Swift",
        "Dart",
        "PHP",
        "Ruby",
        "Scala",
        "Perl",
        "R",
        "MATLAB",
        "Objective-C",
        "Visual Basic",
        "Assembly",
        "COBOL",
        "Fortran",
        "HTML",
        "HTML5",
        "CSS",
        "CSS3",
        "SASS",
        "SCSS",
        "Bootstrap",
        "Tailwind",
        "Tailwind CSS",
        "Material UI",
        "MUI",
        "Chakra UI",
        "React",
        "React.js",
        "Angular",
        "Vue",
        "Vue.js",
        "Svelte",
        "Next.js",
        "Nuxt.js",
        "Gatsby",
        "Node.js",
        "Express",
        "Express.js",
        "NestJS",
        "Django",
        "Flask",
        "FastAPI",
        "Spring",
        "Spring Boot",
        "Laravel",
        "ASP.NET",
        ".NET",
        "Ruby on Rails",
        "Android",
        "Android Studio",
        "Kotlin Android",
        "Java Android",
        "iOS",
        "SwiftUI",
        "UIKit",
        "Flutter",
        "React Native",
        "Xamarin",
        "Ionic",
        "SQL",
        "MySQL",
        "PostgreSQL",
        "SQLite",
        "Oracle",
        "Microsoft SQL Server",
        "SQL Server",
        "MariaDB",
        "MongoDB",
        "Redis",
        "Cassandra",
        "DynamoDB",
        "CouchDB",
        "Firebase",
        "Firestore",
        "Neo4j",
        "Elasticsearch",
        "REST API",
        "RESTful API",
        "GraphQL",
        "SOAP",
        "WebSocket",
        "gRPC",
        "API Development",
        "Microservices",
        "Serverless",
        "OAuth",
        "OAuth2",
        "JWT",
        "OpenAPI",
        "Swagger",
        "Postman",
        "AWS",
        "Amazon Web Services",
        "Azure",
        "Microsoft Azure",
        "Google Cloud",
        "GCP",
        "Oracle Cloud",
        "IBM Cloud",
        "EC2",
        "S3",
        "Lambda",
        "ECS",
        "EKS",
        "CloudFormation",
        "CloudWatch",
        "Azure Functions",
        "Azure DevOps",
        "Google Cloud Functions",
        "Docker",
        "Kubernetes",
        "Jenkins",
        "GitHub Actions",
        "GitLab CI",
        "CircleCI",
        "Travis CI",
        "CI/CD",
        "Continuous Integration",
        "Continuous Deployment",
        "Terraform",
        "Ansible",
        "Chef",
        "Puppet",
        "Helm",
        "Prometheus",
        "Grafana",
        "Git",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "SVN",
        "Version Control",
        "Artificial Intelligence",
        "AI",
        "Machine Learning",
        "Deep Learning",
        "Natural Language Processing",
        "NLP",
        "Computer Vision",
        "Generative AI",
        "Large Language Models",
        "LLM",
        "Reinforcement Learning",
        "TensorFlow",
        "PyTorch",
        "Keras",
        "Scikit-learn",
        "Scikit Learn",
        "Pandas",
        "NumPy",
        "SciPy",
        "Matplotlib",
        "Seaborn",
        "OpenCV",
        "Hugging Face",
        "Transformers",
        "LangChain",
        "LlamaIndex",
        "OpenAI API",
        "Prompt Engineering",
        "Fine-tuning",
        "RAG",
        "Retrieval Augmented Generation",
        "Data Science",
        "Data Analysis",
        "Data Analytics",
        "Big Data",
        "Data Mining",
        "Data Visualization",
        "Statistical Analysis",
        "Predictive Analytics",
        "Power BI",
        "Tableau",
        "Looker",
        "Excel",
        "Advanced Excel",
        "VBA",
        "Jupyter",
        "Apache Spark",
        "Hadoop",
        "Hive",
        "Kafka",
        "Databricks",
        "Data Engineering",
        "ETL",
        "ELT",
        "Data Pipeline",
        "Data Warehouse",
        "Data Lake",
        "Snowflake",
        "Airflow",
        "Apache Airflow",
        "dbt",
        "Apache Spark",
        "Apache Flink",
        "Kafka",
        "Data Modeling",
        "Cybersecurity",
        "Information Security",
        "Network Security",
        "Application Security",
        "Cloud Security",
        "Cyber Defense",
        "Ethical Hacking",
        "Penetration Testing",
        "Pen Testing",
        "Vulnerability Assessment",
        "Security Auditing",
        "Kali Linux",
        "Metasploit",
        "Burp Suite",
        "Wireshark",
        "Nmap",
        "OWASP",
        "OWASP Top 10",
        "SIEM",
        "SOC",
        "Incident Response",
        "Digital Forensics",
        "Cryptography",
        "Encryption",
        "Firewall",
        "IDS",
        "IPS",
        "Linux",
        "Ubuntu",
        "Windows Server",
        "Unix",
        "Bash",
        "Shell Scripting",
        "PowerShell",
        "Computer Networks",
        "Networking",
        "TCP/IP",
        "DNS",
        "DHCP",
        "HTTP",
        "HTTPS",
        "VPN",
        "Routing",
        "Switching",
        "Cisco",
        "Cisco Networking",
        "CCNA",
        "LAN",
        "WAN",
        "Firewall",
        "Software Testing",
        "Quality Assurance",
        "QA",
        "Manual Testing",
        "Automation Testing",
        "Unit Testing",
        "Integration Testing",
        "System Testing",
        "Regression Testing",
        "Performance Testing",
        "Load Testing",
        "API Testing",
        "Selenium",
        "Cypress",
        "Playwright",
        "Jest",
        "Mocha",
        "JUnit",
        "PyTest",
        "TestNG",
        "Postman",
        "Software Engineering",
        "Object Oriented Programming",
        "OOP",
        "Data Structures",
        "Algorithms",
        "Design Patterns",
        "System Design",
        "Software Architecture",
        "Agile",
        "Scrum",
        "Kanban",
        "SDLC",
        "UML",
        "SOLID Principles",
        "Clean Code",
        "FinTech",
        "Financial Technology",
        "Digital Banking",
        "Online Banking",
        "Mobile Banking",
        "Open Banking",
        "Banking APIs",
        "Payment Gateway",
        "Payment Processing",
        "Digital Payments",
        "Electronic Payments",
        "Payment Systems",
        "Stripe",
        "PayPal",
        "Square",
        "Visa",
        "Mastercard",
        "SWIFT",
        "SEPA",
        "Blockchain",
        "Cryptocurrency",
        "Bitcoin",
        "Ethereum",
        "Smart Contracts",
        "Solidity",
        "Web3",
        "DeFi",
        "NFT",
        "Fraud Detection",
        "Fraud Prevention",
        "Risk Management",
        "Credit Risk",
        "Market Risk",
        "Operational Risk",
        "Financial Risk",
        "AML",
        "Anti Money Laundering",
        "KYC",
        "Know Your Customer",
        "Financial Modeling",
        "Financial Analysis",
        "Investment Analysis",
        "Portfolio Management",
        "Algorithmic Trading",
        "Quantitative Finance",
        "Quantitative Analysis",
        "Trading Systems",
        "Accounting",
        "Financial Accounting",
        "Management Accounting",
        "Corporate Finance",
        "Investment Banking",
        "Commercial Banking",
        "Financial Planning",
        "Financial Reporting",
        "Budgeting",
        "Forecasting",
        "Auditing",
        "Taxation",
        "GAAP",
        "IFRS",
        "SAP",
        "QuickBooks",
        "Bloomberg Terminal",
        "Excel Finance",
        "Engineering Design",
        "CAD",
        "CAM",
        "CAE",
        "Technical Drawing",
        "Engineering Drawing",
        "3D Modeling",
        "Simulation",
        "Finite Element Analysis",
        "FEA",
        "Computational Fluid Dynamics",
        "CFD",
        "MATLAB",
        "Simulink",
        "ANSYS",
        "SolidWorks",
        "AutoCAD",
        "CATIA",
        "Creo",
        "Fusion 360",
        "Electrical Engineering",
        "Electronics",
        "Circuit Design",
        "Digital Electronics",
        "Analog Electronics",
        "Power Electronics",
        "Control Systems",
        "Signal Processing",
        "Digital Signal Processing",
        "DSP",
        "Embedded Systems",
        "Microcontrollers",
        "Microprocessors",
        "Arduino",
        "Raspberry Pi",
        "ESP32",
        "STM32",
        "PIC",
        "ARM",
        "FPGA",
        "VHDL",
        "Verilog",
        "SystemVerilog",
        "PCB Design",
        "PCB",
        "Altium Designer",
        "KiCad",
        "Eagle CAD",
        "PLC",
        "SCADA",
        "Industrial Automation",
        "Robotics",
        "Instrumentation",
        "Power Systems",
        "Electrical Machines",
        "Power Generation",
        "Power Transmission",
        "Power Distribution",
        "Renewable Energy",
        "Solar Energy",
        "Wind Energy",
        "Smart Grid",
        "Robotics",
        "Robot Operating System",
        "ROS",
        "ROS2",
        "Automation",
        "Industrial Robotics",
        "Computer Vision",
        "Motion Planning",
        "Robot Control",
        "Sensors",
        "Actuators",
        "IoT",
        "Internet of Things",
        "Mechanical Engineering",
        "Thermodynamics",
        "Fluid Mechanics",
        "Heat Transfer",
        "Mechanics",
        "Machine Design",
        "Manufacturing",
        "Manufacturing Processes",
        "Mechanical Design",
        "CAD Design",
        "CNC",
        "CNC Machining",
        "3D Printing",
        "Additive Manufacturing",
        "HVAC",
        "Automotive Engineering",
        "Civil Engineering",
        "Structural Engineering",
        "Structural Analysis",
        "Construction",
        "Construction Management",
        "Geotechnical Engineering",
        "Transportation Engineering",
        "Environmental Engineering",
        "Surveying",
        "GIS",
        "Geographic Information Systems",
        "Revit",
        "Civil 3D",
        "STAAD Pro",
        "ETABS",
        "SAP2000",
        "Primavera",
        "Chemical Engineering",
        "Process Engineering",
        "Process Design",
        "Chemical Processes",
        "Process Control",
        "Mass Transfer",
        "Heat Transfer",
        "Reaction Engineering",
        "Process Simulation",
        "Aspen Plus",
        "Aspen HYSYS",
        "Telecommunications",
        "Telecommunication Engineering",
        "Wireless Communication",
        "Digital Communication",
        "RF Engineering",
        "RF Design",
        "5G",
        "4G",
        "LTE",
        "VoLTE",
        "Fiber Optics",
        "Optical Communication",
        "Satellite Communication",
        "Antenna Design",
        "Media",
        "Digital Media",
        "Mass Communication",
        "Broadcasting",
        "Journalism",
        "News Production",
        "Content Creation",
        "Content Writing",
        "Copywriting",
        "Technical Writing",
        "Creative Writing",
        "Script Writing",
        "Storytelling",
        "Video Editing",
        "Video Production",
        "Film Production",
        "Film Editing",
        "Cinematography",
        "Photography",
        "Photo Editing",
        "Motion Graphics",
        "Animation",
        "2D Animation",
        "3D Animation",
        "Visual Effects",
        "VFX",
        "Adobe Premiere Pro",
        "Premiere Pro",
        "Adobe After Effects",
        "After Effects",
        "Adobe Photoshop",
        "Photoshop",
        "Adobe Illustrator",
        "Illustrator",
        "Adobe Lightroom",
        "Lightroom",
        "DaVinci Resolve",
        "Final Cut Pro",
        "Blender",
        "Maya",
        "Cinema 4D",
        "UI Design",
        "UX Design",
        "UI/UX",
        "User Experience",
        "User Interface",
        "Interaction Design",
        "Product Design",
        "Graphic Design",
        "Visual Design",
        "Design Thinking",
        "Wireframing",
        "Prototyping",
        "Usability Testing",
        "Figma",
        "Adobe XD",
        "Sketch",
        "Canva",
        "InDesign",
        "Digital Marketing",
        "Social Media Marketing",
        "Content Marketing",
        "Email Marketing",
        "Search Engine Optimization",
        "SEO",
        "Search Engine Marketing",
        "SEM",
        "Google Ads",
        "Facebook Ads",
        "Instagram Marketing",
        "TikTok Marketing",
        "LinkedIn Marketing",
        "Affiliate Marketing",
        "Influencer Marketing",
        "Brand Management",
        "Google Analytics",
        "Product Development",
        "Project Management",
        "Technical Project Management",
        "Program Management",
        "Business Analysis",
        "Requirements Analysis",
        "Requirements Engineering",
        "Jira",
        "Confluence",
        "Trello",
        "Asana",
        "Notion",
        "Microsoft Project",
        "ERP",
        "SAP",
        "SAP S/4HANA",
        "Oracle ERP",
        "Salesforce",
        "Microsoft Dynamics",
        "CRM",
        "Customer Relationship Management",
        "Blockchain",
        "Ethereum",
        "Bitcoin",
        "Solidity",
        "Smart Contract",
        "Smart Contracts",
        "Web3",
        "DeFi",
        "Decentralized Applications",
        "DApp",
        "Cryptocurrency",
        "Hyperledger",
        "Bioinformatics",
        "Computational Biology",
        "Healthcare IT",
        "HealthTech",
        "Medical Imaging",
        "Medical Informatics",
        "Genomics",
        "Genetic Algorithms",
        "Leadership",
        "Communication",
        "Teamwork",
        "Problem Solving",
        "Critical Thinking",
        "Time Management",
        "Project Management",
        "Negotiation",
        "Presentation Skills",
        "Public Speaking",
        "Customer Service",
        "Analytical Skills",
        "Decision Making"
    ];

    const foundKeywords = keywordDatabase.filter(skill =>
        jobDescription.toLowerCase().includes(skill.toLowerCase())
    );

    return foundKeywords;

}

module.exports = extractjobSkills;