### fetch all resume
GET  http://localhost:5000/api/resume/fetchresume
auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE1YTZhYTc2MmU4ZTYwOWZmZjVjNDg5In0sImlhdCI6MTc4NDMxMjYyNn0.rz8AHeJc7eiHWWGjUn4MywvhNJGowZZ4iM0ehoWXmLU

### upload resume

POST http://localhost:5000/api/resume/addresume
auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE1YTZhYTc2MmU4ZTYwOWZmZjVjNDg5In0sImlhdCI6MTc4NDMxMjYyNn0.rz8AHeJc7eiHWWGjUn4MywvhNJGowZZ4iM0ehoWXmLU
Content-Type: application/json

{
  "text": "John Doe - Software Engineer with 3 years experience in React and Node.js. Test entry to verify Add Resume functionality"
}



###delete a resume 
DELETE http://localhost:5000/api/resume/deleteresume/6a5f587b01064b31af4e2ccc
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNmE1YTZhYTc2MmU4ZTYwOWZmZjVjNDg5In0sImlhdCI6MTc4NDMxMjYyNn0.rz8AHeJc7eiHWWGjUn4MywvhNJGowZZ4iM0ehoWXmLU
Content-Type: application/json

{
  "text": "Sample resume text",
  "resumepath": "uploads/johndoe_resume.pdf"
}
